### PR TITLE
First unit branch

### PR DESCRIPTION
**Pull request by ginaserakalala**

### CODE REVIEW

**Comment by anirbandas18** [comment]
1. remove junit 4 dependency
2. what is the use of slf4j dependency?

**Comment by anirbandas18** [comment]
test cases look good

**Comment by ginaenviro** [comment]
I wanted to create some logs with slf4j but Ive removed it

**Comment by ginaserakalala** [comment]
> * remove junit 4 dependency
> * what is the use of slf4j dependency?

I removed the dependencies in pom

**Pull request merged**
